INSERT INTO ingredients (name, default_unit, shopping_category) VALUES
  ('Tomate', 'ud', 'verduras'),
  ('Cebolla', 'ud', 'verduras'),
  ('Ajo', 'diente', 'verduras'),
  ('Patata', 'ud', 'verduras'),
  ('Zanahoria', 'ud', 'verduras'),
  ('Calabacín', 'ud', 'verduras'),
  ('Pimiento rojo', 'ud', 'verduras'),
  ('Pimiento verde', 'ud', 'verduras'),
  ('Brócoli', 'g', 'verduras'),
  ('Espinacas', 'g', 'verduras'),
  ('Lechuga', 'ud', 'verduras'),
  ('Perejil', 'pellizco', 'verduras'),
  ('Albahaca', 'pellizco', 'verduras'),
  ('Jengibre', 'g', 'verduras'),
  ('Limón', 'ud', 'frutas'),
  ('Manzana', 'ud', 'frutas'),
  ('Plátano', 'ud', 'frutas'),
  ('Pollo', 'g', 'carne'),
  ('Pechuga de pollo', 'g', 'carne'),
  ('Ternera picada', 'g', 'carne'),
  ('Salmón', 'g', 'pescado'),
  ('Atún en lata', 'ud', 'pescado'),
  ('Gambas', 'g', 'pescado'),
  ('Huevos', 'ud', 'lacteos'),
  ('Leche', 'ml', 'lacteos'),
  ('Mantequilla', 'g', 'lacteos'),
  ('Queso rallado', 'g', 'lacteos'),
  ('Mozzarella', 'g', 'lacteos'),
  ('Pan', 'ud', 'panaderia'),
  ('Arroz', 'g', 'despensa'),
  ('Pasta', 'g', 'despensa'),
  ('Lentejas', 'g', 'despensa'),
  ('Garbanzos', 'g', 'despensa'),
  ('Alubias', 'g', 'despensa'),
  ('Harina', 'g', 'despensa'),
  ('Azúcar', 'g', 'despensa'),
  ('Levadura', 'g', 'despensa'),
  ('Aceite de oliva', 'ml', 'despensa'),
  ('Sal', 'pellizco', 'despensa'),
  ('Pimienta negra', 'pellizco', 'despensa'),
  ('Salsa de tomate', 'ml', 'despensa'),
  ('Mostaza', 'cucharadita', 'despensa'),
  ('Vinagre', 'ml', 'despensa'),
  ('Miel', 'cucharada', 'despensa'),
  ('Comino', 'pellizco', 'despensa'),
  ('Pimentón', 'pellizco', 'despensa'),
  ('Orégano', 'pellizco', 'despensa'),
  ('Caldo de pollo', 'ml', 'despensa'),
  ('Vino blanco', 'ml', 'bebidas');
